services:
  backend:
    build:
      context: .
      # Ha ARM hoston vagy (Apple Silicon), ez segít:
      platforms:
        - linux/arm64
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DATABASE}?sslmode=disable
      REDIS_URL: redis://${REDIS_HOST}:${REDIS_PORT}
      PORT: 8080
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${PG_USERNAME} -d ${PG_DATABASE}']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    # Ha csak sima Redis kell:
    image: redis:7-alpine
    # Ha a logban látott modulok kellenek (Bloom/Search/JSON/TS), akkor:
    # image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379' # csak akkor kell, ha hostról is akarsz csatlakozni
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
