version: '3.8'
services:
  backend:
    build:
      context: .
      # Ha ARM hoston vagy (Apple Silicon), ez segít:
      platforms:
        - linux/arm64
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # DATABASE_URL: postgres://user:password@db:5432/dbname
      # REDIS_URL: redis://redis:6379 # <-- Ezt fogja olvasni a backend
      # Alternatív bontva:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d dbname']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    # Ha csak sima Redis kell:
    image: redis:7-alpine
    # Ha a logban látott modulok kellenek (Bloom/Search/JSON/TS), akkor:
    # image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379' # csak akkor kell, ha hostról is akarsz csatlakozni
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
